#!/bin/bash

curl -X PUT http://localhost:8080/api/repos/rh-pooled-jms/tags/master-untested -d @- <<EOF
{
    "build_id": "197",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/pooled-jms-maven-master-rhel/detail/central-ci/197/pipeline",
    "artifacts": {
        "pooled-jms-maven": {
            "type": "maven",
            "repository_url": "http://rhm.usersys.redhat.com/zips/packages/pooled-jms/20180814.6dda44a/",
            "group_id": "org.messaginghub",
            "artifact_id": "pooled-jms",
            "version": "1.0.4-SNAPSHOT"
        }
    }
}
EOF

curl -X PUT http://localhost:8080/api/repos/rh-qpid-jms/tags/master-untested -d @- <<EOF
{
    "build_id": "877",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/jms-maven-master-rhel/detail/central-ci/877/pipeline",
    "artifacts": {
        "library": {
            "type": "maven",
            "repository_url": "http://rhm.usersys.redhat.com/zips/packages/qpid-jms/20180608.ccf38d7/",
            "group_id": "org.apache.qpid",
            "artifact_id": "qpid-jms-client",
            "version": "0.33.0-SNAPSHOT"
        }
    }
}
EOF

curl -X PUT http://localhost:8080/api/repos/rh-qpid-dispatch/tags/master-untested -d @- <<EOF
{
    "build_id": "14",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/dispatch-rpm-master-rhel/detail/central-ci/14/pipeline",
    "artifacts": {
        "qpid-dispatch-router-el7-rpm": {
            "type": "rpm",
            "repository_url": "http://rhm.usersys.redhat.com/yum/packages/qpid-dispatch/el7/20180816.483b929/x86_64/",
            "name": "qpid-dispatch-router",
            "version": "1.4.0",
            "release": "20180816.483b929.el7"
        },
        "amq-interconnect-container": {
            "type": "container",
            "registry_url": "https://registry.access.redhat.com",
            "repository": "amq-interconnect-1",
            "image_id": "8e996ec51141"
        }
    }
}
EOF

curl -X PUT http://localhost:8080/api/repos/rh-qpid-proton/tags/master-untested -d @- <<EOF
{
    "build_id": "XXX",
    "build_url": "XXX",
    "artifacts": {
        "python-qpid-proton-el7-rpm": {
            "type": "rpm",
            "repository_url": "http://rhm.usersys.redhat.com/yum/packages/qpid-proton/el7/20180816.803a47e/x86_64/",
            "name": "python-qpid-proton",
            "version": "0.25.0",
            "release": "20180816.803a47e.el7"
        },
        "qpid-proton-c-devel-el7-rpm": {
            "type": "rpm",
            "repository_url": "http://rhm.usersys.redhat.com/yum/packages/qpid-proton/el7/20180816.803a47e/x86_64/",
            "name": "qpid-proton-c-devel",
            "version": "0.25.0",
            "release": "20180816.803a47e.el7"
        },
        "qpid-proton-cpp-devel-el7-rpm": {
            "type": "rpm",
            "repository_url": "http://rhm.usersys.redhat.com/yum/packages/qpid-proton/el7/20180816.803a47e/x86_64/",
            "name": "qpid-proton-cpp-devel",
            "version": "0.25.0",
            "release": "20180816.803a47e.el7"
        }
    }
}
EOF
