#!/bin/bash

if [[ -z $1 ]]; then
    url=http://localhost:8080
else
    url=$1
fi

set -ex

curl -X PUT $url/api/repos/rh-pooled-jms-dist/branches/master/tags/tested -d @- <<EOF
{
    "build_id": "196",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/pooled-jms-maven-master-rhel/detail/central-ci/196/pipeline",
    "artifacts": {
        "pooled-jms-maven": {
            "type": "maven",
            "repository_url": "http://rhm.usersys.redhat.com/zips/packages/pooled-jms/20180809.35558e5/",
            "group_id": "org.messaginghub",
            "artifact_id": "pooled-jms",
            "version": "1.0.3-SNAPSHOT"
        }
    }
}
EOF

curl -X PUT $url/api/repos/rh-pooled-jms-dist/branches/master/tags/untested -d @- <<EOF
{
    "build_id": "197",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/pooled-jms-maven-master-rhel/detail/central-ci/197/pipeline",
    "artifacts": {
        "pooled-jms-maven": {
            "type": "maven",
            "repository_url": "http://rhm.usersys.redhat.com/zips/packages/pooled-jms/20180814.6dda44a/",
            "group_id": "org.messaginghub",
            "artifact_id": "pooled-jms",
            "version": "1.0.4-SNAPSHOT"
        }
    }
}
EOF

curl -X PUT $url/api/repos/rh-qpid-jms-dist/branches/master/tags/untested -d @- <<EOF
{
    "build_id": "877",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/jms-maven-master-rhel/detail/central-ci/877/pipeline",
    "artifacts": {
        "library": {
            "type": "maven",
            "repository_url": "http://rhm.usersys.redhat.com/zips/packages/qpid-jms/20180608.ccf38d7/",
            "group_id": "org.apache.qpid",
            "artifact_id": "qpid-jms-client",
            "version": "0.33.0-SNAPSHOT"
        }
    }
}
EOF

curl -X PUT $url/api/repos/rh-qpid-dispatch-dist-el7/branches/master/tags/untested -d @- <<EOF
{
    "build_id": "14",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/dispatch-rpm-master-rhel/detail/central-ci/14/pipeline",
    "artifacts": {
        "qpid-dispatch-router": {
            "type": "rpm",
            "repository_url": "http://rhm.usersys.redhat.com/yum/packages/qpid-dispatch/el7/20180816.483b929/x86_64/",
            "name": "qpid-dispatch-router",
            "version": "1.4.0",
            "release": "14.483b929c.el7"
        }
    }
}
EOF

# XXX Trouble here if I don't disable 100 continue
curl -X PUT -H 'Expect:' $url/api/repos/rh-qpid-proton-dist-el7/branches/master/tags/tested -d @- <<EOF
{
    "build_id": "1198",
    "build_url": "https://amq-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/proton-rpm-master-rhel/job/central-ci/1198/",
    "artifacts": {
        "python-qpid-proton": {
            "type": "rpm",
            "repository_url": "http://files.example.net/rh-qpid-proton-dist-el7/master/tested/1198.803a47e1",
            "name": "python-qpid-proton",
            "version": "0.25.0",
            "release": "1198.803a47e1.el7"
        },
        "qpid-proton-c-devel": {
            "type": "rpm",
            "repository_url": "http://files.example.net/rh-qpid-proton-dist-el7/master/tested/1198.803a47e1",
            "name": "qpid-proton-c-devel",
            "version": "0.25.0",
            "release": "1198.803a47e1.el7"
        },
        "qpid-proton-cpp-devel": {
            "type": "rpm",
            "repository_url": "http://files.example.net/rh-qpid-proton-dist-el7/master/tested/1198.803a47e1",
            "name": "qpid-proton-cpp-devel",
            "version": "0.25.0",
            "release": "1198.803a47e1.el7"
        }
    }
}
EOF
