#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

enable_logging(level="notice")

server = start_process("python3 server/app.py")

try:
    sleep(0.5)

    call("curl -X PUT --data-ascii '{{\"abc\": 123}}' http://localhost:8080/api/tags/rh-qpid-proton-j:master:untested")
    call("curl -X GET http://localhost:8080/api/tags/rh-qpid-proton-j:master:untested", quiet=True)
    call("curl -X DELETE http://localhost:8080/api/tags/rh-qpid-proton-j:master:untested")
    call("curl -X GET http://localhost:8080/api/tags", quiet=True)
finally:
    terminate_process(server)
