#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

tag_1 = {
    "repository": "rh-qpid-jms",
    "repository_url": "http://git.host.prod.eng.bos.redhat.com/git/rh-qpid-jms.git",
    "branch": "0.34.0-amq",
    "name": "tested",
    "commit": "16dc03dc8075e6600342b1dcdcafc5d28b7ffde5",
    "artifacts": {
        "client-maven": {
            "type": "maven",
            "group": "org.apache.qpid",
            "artifact": "qpid-jms-client",
            "version": "0.34.0.redhat-00002",
            "repository_url": "http://download-node-02.eng.bos.redhat.com/devel/candidates/amq/AMQ-CLIENTS-2.1.0/JMS-maven-repo/maven-repository",
        },
        "client-zip": {
            "type": "file",
            "url": "http://download-node-02.eng.bos.redhat.com/devel/candidates/amq/AMQ-CLIENTS-2.1.0/qpid-jms-0.34.0.redhat-00002-bin.zip",
        },
    },
}

curl_options = "--fail -o /dev/null -s -w '%{http_code} (%{size_download})\\n' -H 'Content-Type: application/json'"

def put(url, data):
    with temp_file() as data_file:
        write_json(data_file, data)
        print(f"PUT {url} -> ", end="", flush=True)
        call("curl -X PUT {} --data @{} {}", url, data_file, curl_options)

def get(url):
    print(f"GET {url} -> ", end="", flush=True)
    call("curl {} {}", url, curl_options)

def delete(url):
    print(f"DELETE {url} -> ", end="", flush=True)
    call("curl -X DELETE {} {}", url, curl_options)

enable_logging(level="warn")

server = start_process("python3 server/app.py")

try:
    sleep(0.5)

    put("http://localhost:8080/api/tags/rh-qpid-jms:0.34.0-amq:tested", tag_1)

    get("http://localhost:8080/api/tags")
    get("http://localhost:8080/api/tags/rh-qpid-jms:0.34.0-amq:tested")
    get("http://localhost:8080/api/tags/rh-qpid-jms:0.34.0-amq:tested/artifacts")
    get("http://localhost:8080/api/tags/rh-qpid-jms:0.34.0-amq:tested/artifacts/client-zip")

    delete("http://localhost:8080/api/tags/rh-qpid-jms:0.34.0-amq:tested")

    get("http://localhost:8080/api/tags")
finally:
    terminate_process(server)
